// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package srv

import (
	"context"
	"github.com/aserto-dev/aserto-idp-plugin-aserto/pkg/mocks"
	"github.com/aserto-dev/idp-plugin-sdk/plugin"
	"github.com/golang/mock/gomock"
)

// Injectors from wire.go:

func NewAsertoPlugin() *AsertoPlugin {
	asertoPlugin := &AsertoPlugin{}
	return asertoPlugin
}

func NewTestAsertoPlugin(ctrl *gomock.Controller, op plugin.OperationType) *AsertoPlugin {
	contextContext := context.Background()
	mockDirectoryClient := mocks.NewMockDirectoryClient(ctrl)
	mockDirectory_LoadUsersClient := mocks.NewMockDirectory_LoadUsersClient(ctrl)
	asertoPlugin := &AsertoPlugin{
		ctx:             contextContext,
		dirClient:       mockDirectoryClient,
		loadUsersStream: mockDirectory_LoadUsersClient,
		op:              op,
	}
	return asertoPlugin
}
